---
build:
  parallel:
    matrix:
      - image: alpine
        tag: latest
  retry: 1
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  script:
    - echo "building..."
    - image=${image} tag=${tag} molecule test
  stage: build
image: buluma/github-action-molecule:4.0.5
integration_tests:
  script: echo "running integration tests..."
  stage: test
services:
  - docker:dind
unit_tests:
  script: echo "running unit tests..."
  stage: test
variables:
  DOCKER_HOST: tcp://docker:2375
  PY_COLORS: 1
