---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  run_once: true
- name: Install dns
  ansible.builtin.package:
    name: "{{ dns_packages }}"
    state: present
- name: Create directories
  ansible.builtin.file:
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    path: "{{ item.path }}"
    state: directory
  loop:
    - group: "{{ dns_group }}"
      mode: "1770"
      owner: "{{ dns_owner }}"
      path: "{{ dns_datadir }}"
    - group: root
      mode: "0755"
      owner: root
      path: "{{ dns_confdir }}"
  loop_control:
    label: "{{ item.path }}"
- name: Create group
  ansible.builtin.group:
    name: "{{ dns_group }}"
    state: present
- name: Create user
  ansible.builtin.user:
    name: "{{ dns_owner }}"
    state: present
    system: true
- name: Generate rndc key
  ansible.builtin.command:
    cmd: rndc-confgen -a -c "{{ dns_confdir }}/rndc.key"
    creates: "{{ dns_confdir }}/rndc.key"
- name: Set permissions on rndc key file
  ansible.builtin.file:
    group: "{{ dns_group }}"
    mode: "0640"
    owner: "{{ dns_owner }}"
    path: "{{ dns_confdir }}/rndc.key"
- name: Get the hints/root file
  ansible.builtin.get_url:
    dest: "{{ dns_datadir }}/named.root"
    group: "{{ dns_group }}"
    mode: "0640"
    owner: "{{ dns_owner }}"
    url: https://www.internic.net/domain/named.root
    validate_certs: "{{ dns_validate_certs }}"
  notify:
    - Rndc reload
  when:
    - dns_caching_dns
- name: Create zone files
  ansible.builtin.template:
    dest: "{{ dns_datadir }}/{{ item.name }}.conf"
    group: "{{ dns_group }}"
    mode: "0640"
    owner: "{{ dns_owner }}"
    src: zone.j2
  loop: "{{ dns_zones }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Rndc reload
  when:
    - item.type is undefined or item.type == "master"
- name: Add zones to configuration
  ansible.builtin.template:
    backup: true
    dest: "{{ dns_confdir }}/named.conf"
    group: "{{ dns_group }}"
    mode: "0640"
    owner: "{{ dns_owner }}"
    src: named.conf.j2
    validate: named-checkconf -zj %s
  notify:
    - Restart dns
- name: Place systemd override
  when:
    - ansible_service_mgr == "systemd"
  block:
    - name: Create service.d {{ dns_service }}
      ansible.builtin.file:
        mode: "0755"
        path: /etc/systemd/system/{{ dns_service }}.service.d
        state: directory
    - name: Place override.conf
      ansible.builtin.copy:
        dest: /etc/systemd/system/{{ dns_service }}.service.d/override.conf
        group: root
        mode: "0644"
        owner: root
        src: override.conf
    - name: Systemctl daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
      changed_when: false
- name: Start and enable dns
  ansible.builtin.service:
    enabled: true
    name: "{{ dns_service }}"
    state: started
